Adds new fonts to Storybook config and website
mongodb/leafygreen-ui pull request #1088
Opened 2022-01-12 18:56 UTC by TheSonOfThomp

## ✍️ Proposed changes

🎟 _Jira ticket:_ [Name of ticket](https://jira.mongodb.org/browse/[name-of-ticket])

## 🛠 Types of changes

- [ ] Tooling (updates to workspace config or internal tooling)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## ✅ Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have run `yarn changeset` and documented my changes

- [ ] I have added my new package to the global tsconfig
- [ ] I have added my new package to the Table of Contents on the global README

## 🧪 How to test changes

## 💬 Further comments

2022-01-12 19:56 UTC, DesignerDave requested changes
Couple notes. Also, we do need to add the new font family to our tokens package.

2022-01-12 19:56 UTC, DesignerDave commented on website/styles/globals.tsx
> +    font-family: 'Euclid', 'Akzidenz', 'Helvetica Neue', Helvetica, Arial,
I don't think we should flip this switch yet.

2022-01-12 19:56 UTC, DesignerDave commented on storybook/preview-head.html
> +    font-family: 'Euclid', 'Akzidenz', Helvetica, Arial, sans-serif;
Are we able to do this selectively? Not all components are going to be able to use this yet.

2022-01-13 18:11 UTC, TheSonOfThomp commented on storybook/preview-head.html
> +    font-family: 'Euclid';
Call this "Euclid Circular A"

2022-01-13 18:11 UTC, TheSonOfThomp commented on storybook/preview-head.html
> +    font-family: 'Value';
Call this "MongoDB Value Serif"

2022-01-13 18:12 UTC, TheSonOfThomp commented on website/styles/globals.tsx
> +    font-family: 'Value Serif';
Call this "MongoDB Value Serif"

2022-01-13 18:12 UTC, TheSonOfThomp commented on website/styles/globals.tsx
> +    font-family: 'Euclid';
Call this "Euclid Circular A"

2022-01-13 18:12 UTC, TheSonOfThomp commented on storybook/preview-head.html
> +    font-weight: 700, bold;
Remove "bold"

2022-01-13 18:12 UTC, TheSonOfThomp commented on storybook/preview-head.html
> +    font-weight: 600;
This is "bold"

2022-01-13 18:13 UTC, TheSonOfThomp commented on storybook/preview-head.html
> +    font-weight: 100, 200, 300;
Just call this `300`

2022-01-19 19:45 UTC, DesignerDave approved these changes

2022-01-19 20:02 UTC, DesignerDave commented on storybook/preview-head.html
> +    font-weight: 700;
We should be setting this as the bold font weight I believe as well.

2022-01-19 20:43 UTC, merged