PD-1620 Adds `isGlyph` property to generic Icon
mongodb/leafygreen-ui pull request #1243
Opened 2022-05-02 16:24 UTC by TheSonOfThomp

## ✍️ Proposed changes

Adds the `isGlyph` property to the generic `<Icon />` component, meaning it can now be used in Select and Combobox options. 

Additionally, overloads the `isComponentGlyph` function to accept either a `ReactNode` and `ComponentType`

🎟 _Jira ticket:_ [PD-1620](https://jira.mongodb.org/browse/PD-1620)

## 🛠 Types of changes

- [ ] Tooling (updates to workspace config or internal tooling)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Style change (purely visual updates; if this is the case, attach a screenshot below!)

## ✅ Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have run `yarn changeset` and documented my changes

- [ ] I have added my new package to the global tsconfig
- [ ] I have added my new package to the Table of Contents on the global README

## 🧪 How to test changes

## 💬 Further comments

## Feedback Levels

Please try to mark your comments with one of these levels

1. Praise (👏 🚀 🔥 🍾)
2. Opinions, Ideas, Suggestions (💡 👀)
3. Let’s discuss @ Code review (🤷 🤔 🧐 )
4. Doesn’t meet agreed upon standards (😬 ⚠️ ‼️)
5. Missing an edge case (🛑 🙅 ❌)
6. Missing core functionality (⛔️ ☣️ 🚧 🌋 💀)

(Note: Use ⌘-⌃-␣ to open the Emoji keyboard!)

2022-05-10 20:54 UTC, spark33 commented on packages/icon/src/isComponentGlyph.ts
> +  // If we've recieved a component function
typos!

2022-05-10 21:09 UTC, spark33 requested changes
I'm wondering if we can leverage `isComponentType` here. Whether it's  `isComponentType(glyph, 'Icon')`,  `isComponentType(glyph, 'LGIcon')`, `isComponentType(glyph, 'Glyph')` or something along those lines.

Adding a custom prop to check for this feels extraneous and not very "React".

2022-05-18 17:00 UTC, TheSonOfThomp commented
> I'm wondering if we can leverage `isComponentType` here. Whether it's `isComponentType(glyph, 'Icon')`, `isComponentType(glyph, 'LGIcon')`, `isComponentType(glyph, 'Glyph')` or something along those lines.
> 
> Adding a custom prop to check for this feels extraneous and not very "React".

I dug a little deeper into this, and while I think this would be a good idea, it breaks how we identify Icon components. 

Currently the `displayName` of any individual icon component is the name of that icon (e.g. `Beaker` etc.). Changing the displayName to `Icon` would break any tests relying on this `displayName`. I think we should file a separate ticket to make this change

2022-05-18 20:52 UTC, spark33 approved these changes

2022-05-18 20:53 UTC, merged