LG-2871 LG-2662 updates toast design
mongodb/leafygreen-ui pull request #1629
Opened 2023-02-17 22:17 UTC by TheSonOfThomp

## ✍️ Proposed changes

Updates basic styling of Toast. Demo: https://thesonofthomp.github.io/leafygreen-ui/?path=/story/components-toast--dismissible

Note: This does _not_ incorporate any new multi-toast behavior

🎟 _Jira ticket:_ 
- [Update Toast design](https://jira.mongodb.org/browse/LG-2871)
- [Reorg. internal directory](https://jira.mongodb.org/browse/LG-2662)

<img width="423" alt="Screen Shot 2023-02-17 at 6 32 03 PM" src="https://user-images.githubusercontent.com/2414030/219816444-71f9e184-7aa2-4aec-bfe0-654f365ded98.png">

## 🛠 Types of changes

- [x] Tooling (updates to workspace config or internal tooling)
- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Style change (purely visual updates; if this is the case, attach a screenshot below!)

## ✅ Checklist

- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [x] I have run `yarn changeset` and documented my changes

- [ ] I have added my new package to the global tsconfig
- [ ] I have added my new package to the Table of Contents on the global README

## 🧪 How to test changes

## 💬 Further comments

## Feedback Levels

Please try to mark your comments with one of these levels

1. Praise (👏 🚀 🔥 🍾)
2. Opinions, Ideas, Suggestions (💡 👀)
3. Let’s discuss @ Code review (🤷 🤔 🧐 )
4. Doesn’t meet agreed upon standards (😬 ⚠️ ‼️)
5. Missing an edge case (🛑 🙅 ❌)
6. Missing core functionality (⛔️ ☣️ 🚧 🌋 💀)

(Note: Use ⌘-⌃-␣ to open the Emoji keyboard!)

2023-02-17 23:53 UTC, sandynguyenn approved these changes
Looks great! Praise (👏 🚀 🔥 🍾)

2023-02-21 21:12 UTC, brookescarlett commented on .changeset/big-parrots-scream.md
> +- Renames `body` to `description` to align with Figma component
Designers will make the body <=> description change on their side

2023-02-21 21:13 UTC, brookescarlett commented on .changeset/big-parrots-scream.md
> +- Renames `body` to `description` to align with Figma component
So let's leave this as is

2023-02-22 00:21 UTC, spark33 requested changes

2023-02-22 00:21 UTC, spark33 commented on packages/toast/src/ProgressBar/ProgressBar.tsx
>        90deg,
Let's move this to a `ProgressBar.styles.ts` if we want to call the restructuring done

2023-02-22 00:21 UTC, spark33 commented on packages/toast/src/Toast/Toast.tsx
> +                baseToastStyle,
ignorable nit: `Styles`, for all style variables

2023-02-22 18:31 UTC, shaneeza reviewed
Looking good. One thing I noticed is that the focus and hover styles for links are not showing up.

2023-02-23 03:18 UTC, spark33 approved these changes

2023-02-23 22:11 UTC, merged