LG-3209: ToastProvider/useToast no longer forces rerender every time the stack changes
mongodb/leafygreen-ui pull request #1743
Opened 2023-05-15 16:58 UTC by bruugey

2023-05-17 14:40 UTC, TheSonOfThomp requested changes
We should add a test suite to verify these fixes

2023-05-17 14:40 UTC, TheSonOfThomp commented on packages/toast/src/ToastContext/ToastReducer/useToastReducer.ts
> +      stack,
Or, I guess it's fine if the methods inside are the same?

2023-05-17 14:40 UTC, TheSonOfThomp commented on .changeset/strong-onions-grow.md
> +Memoizes functions and stack inside of useReducer
Should we add a comment why, and what bug this fixes?

2023-05-19 13:03 UTC, bruugey commented on packages/toast/src/ToastContext/ToastProvider/ToastProvider.tsx
> +  const cachedGetStack = useCallback(() => stack, [stack]);
👍

2023-05-19 13:03 UTC, bruugey commented on packages/toast/src/ToastContext/ToastProvider/ToastProvider.tsx
> +  const value = useMemo(() => {
👍

2023-05-19 15:12 UTC, TheSonOfThomp approved these changes
🍞

2023-05-19 15:39 UTC, merged