LG-3535: Palette click-to-copy
mongodb/leafygreen-ui pull request #2073
Opened 2023-11-09 16:45 UTC by spark33

## ✍️ Proposed changes

🎟 _Jira ticket:_ [LG-3535](https://jira.mongodb.org/browse/LG-3535)

## ✅ Checklist

### For bug fixes, new features & breaking changes

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [x] I have run `yarn changeset` and documented my changes

### For new components

- [ ] I have added my new package to the global tsconfig
- [ ] I have added my new package to the Table of Contents on the global README
- [ ] I have verified the Live Example looks as intended on the design website.

## 🧪 How to test changes

2023-11-09 18:56 UTC, bruugey commented
Looks like we need to `rm` tokens from palette or add it as a dep. 
`@leafygreen-ui/palette is missing devDependencies: @leafygreen-ui/tokens`

2023-11-10 16:26 UTC, shaneeza commented on packages/palette/src/Palette.story.tsx
> +  z-index: 9999;
why so high?

2023-11-10 16:54 UTC, shaneeza requested changes
There's no focus state on the buttons, we should add that in

2023-11-13 19:39 UTC, shaneeza commented on packages/palette/src/Palette.story.tsx
> +  &:focus {
let's make this focus-visible? so it doesn't show up on mouse click

2023-11-13 22:10 UTC, shaneeza approved these changes

2023-11-14 16:08 UTC, merged