LG-3775: Prevent Select from opening on option selection
mongodb/leafygreen-ui pull request #2075
Opened 2023-11-10 15:50 UTC by shaneeza

## ✍️ Proposed changes

🎟 _Jira ticket:_ [LG-3775](https://jira.mongodb.org/browse/LG-3775)

## ✅ Checklist

### For bug fixes, new features & breaking changes

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] I have run `yarn changeset` and documented my changes

### For new components

- [ ] I have added my new package to the global tsconfig
- [ ] I have added my new package to the Table of Contents on the global README
- [ ] I have verified the Live Example looks as intended on the design website.

## 🧪 How to test changes

2023-11-14 16:12 UTC, spark33 requested changes

2023-11-14 16:34 UTC, shaneeza commented on packages/select/src/Select/Select.spec.tsx
> +          await waitForElementToBeRemoved(getByRole('listbox'));
yes! it would fail if its not removed

2023-11-14 16:35 UTC, shaneeza commented on packages/select/src/Select/Select.spec.tsx
> +          await waitForElementToBeRemoved(getByRole('listbox'));
same as above, it would fail it was not removed

2023-11-14 16:36 UTC, shaneeza commented on packages/select/src/Select/Select.spec.tsx
> +          expect(queryByRole('listbox')).not.toBeInTheDocument();
that makes sense, i can add a timeout

2023-11-15 17:37 UTC, spark33 approved these changes

2023-11-15 19:10 UTC, merged